### ISSUE TITLE
Is it still impossible to transmit speed, power and cadence at the same time?

### ISSUE THREAD

**Issue by tzm41** [intelligenate/dfc#10]
Just purchased one from Crowd Supply. But it doesn't look like transmitting all three data has been working?

**Comment by tzm41** [comment]
Alright I guess there's no active effort into this anymore. Time to cancel my order unfortunately...

**Comment by veneman** [comment]
It's definitely still under active development and we've got bunch of new devices being built right now. We had to put the combo power and speed work on the back burner to get the next production run going but are trying some new multi-metric things now.
