### ISSUE TITLE
PeloMon as info to help get Speed

### ISSUE THREAD

**Issue by Stoobiedoo** [intelligenate/dfc#12]
Would any of the work done by Imran Haque be helpful in getting speed to work with the DFC?
https://ihaque.org/tag/pelomon.html
https://github.com/ihaque/pelomon

**Comment by veneman** [comment]
We have a [beta release](https://github.com/intelligenate/dfc/releases/tag/speed-cadence-beta.1) that will broadcast speed and cadence together but not power. We were hoping to get DFC to appear as two separate sensors (power+cadence & speed+cadence) but haven't found a good solution for that. We're now working to make DFC appear as a "fitness machine" which allows sending speed, power, and cadence as one sensor.
