### ISSUE TITLE
Unable to pair FR935

### ISSUE THREAD

**Issue by chipkent** [intelligenate/dfc#14]
I am attempting to pair a FR935 on some new hardware.  The watch does not seem able to identify the device.

The troubleshooting docs indicate:
```
DFC is not showing up on my device or app's pairing screen.
* Verify that DFC is powered on. It will blink for the first three minutes it’s powered on.
```
There does not appear to be a light on my device.

Should I expect this device to work?

**Comment by veneman** [comment]
Closing this out since we've resolved this offline. Unfortunately the FR935 does not appear to work with DFC. This is now noted in the [compatibility table](https://github.com/intelligenate/dfc/blob/main/docs/user-guide.md#compatibility-tables).
