### ISSUE TITLE
Power display empty - Garmin Edge v21.09 update

### ISSUE THREAD

**Issue by steveninmanCubs** [intelligenate/dfc#24]
Hi all,

I've been talking to Garmin support and I can't figure out what is going on. For a couple of years, I pushed DFC data on my Peloton to my Garmin Fenix 6s Pro and it's always worked like a charm. In Feb, I bought a Garmin Edge 840 and I've been pushing to that (easier to see power tied to some workouts I'm doing than looking at my watch).

Last week, I got an alert that Garmin Edge updated to v21.09 and ever since then I can't get power data to show and the connection seems to drop in and out. I've reverted to using my Fenix 6s which is on 26.96 and it's been working fine.

Any ideas about things I could try to get the Edge working again? Should I back ou v21.09 on my Edge and go back to prior one? Are there any logs I can provide?

Thanks,
Steve

**Comment by veneman** [comment]
An update to Fenix and Epix caused some similar issues earlier this year. [Try this update](https://github.com/intelligenate/dfc/releases/tag/power-cadence-beta.4) to fix it. See the [Firmware Updates](https://github.com/intelligenate/dfc/issues/24#firmware-updates) section in the user guide for details on updating.

**Comment by steveninmanCubs** [comment]
That did it. Brilliant!! Something change with how Garmin is feeding the power data over Bluetooth?
