### ISSUE TITLE
Connected but no data 

### ISSUE THREAD

**Issue by Artmidd** [intelligenate/dfc#26]
The dfc connected to garmin but not registering data.  Tightened all wires connected and unconnected powered on and off.  Do I need new dfc?

**Comment by veneman** [comment]
Here’s a few things to check to help narrow down what may be causing issues. 

* Has it worked before or is this the first time you’re connecting DFC to anything?
* What specific device is it that you're trying to connect?
    * [This table](https://github.com/intelligenate/dfc/blob/main/docs/user-guide.md#compatibility-tables) lists which devices are known to work with DFC. 
    * An update for certain Garmin devices (Epix (gen 2), Fenix 6/7, FR265, and possibly others) was causing DFC to continually reset.
    * The updated [firmware that fixes the issue is here](https://github.com/intelligenate/dfc/releases/tag/power-cadence-beta.4). See the [Firmware Updates](https://github.com/intelligenate/dfc/blob/main/docs/user-guide.md#firmware-updates) section in the [User Guide](https://github.com/intelligenate/dfc/blob/main/docs/user-guide.md) for details on updating. 
* Have you tried connecting DFC to any other devices or apps? Kinomap or Zwift are pretty easy to get up and running quickly with DFC.
* Try re-seating the cables and swapping data ports on DFC.
* When you power on DFC do you see a red light blinking through the ports for the first few minutes?
* What are you using to power DFC? It works best using the cable that it comes with it. Using USB-C to USB-C cables can cause issues since DFC draws so little power that some USB-C chargers shut off power to it.
* On your watch under DFC in Sensors does it say "Status Connected"?

**Comment by Artmidd** [comment]
Hi thanks for getting back to me.  It's been working great for almost a year.  Nothing changed in the set up. It's hooked up to a peloton - first edition.  Not the plus. It's on a Fenix 7. I will try the firmware update though it may be too complicated for me! Have not tried connecting to other apps or devices. Tried re seating the cables. See the red light. Using the cord that came with it to power it. It does say status connected.  Just not getting the reading. I think it must be the recent garmin update.  I did notice that it goes in and out, so maybe that's the continual reset.  Was that a. Recent update from garmin that caused the issue?  Thanks again.  Art. On May 23, 2024, at 11:03 PM, Jason Veneman ***@***.***> wrote:﻿
Here’s a few things to check to help narrow down what may be causing issues.

Has it worked before or is this the first time you’re connecting DFC to anything?
What specific device is it that you're trying to connect?

This table lists which devices are known to work with DFC.
An update for certain Garmin devices (Epix (gen 2), Fenix 6/7, FR265, and possibly others) was causing DFC to continually reset.
The updated firmware that fixes the issue is here. See the Firmware Updates section in the User Guide for details on updating.


Have you tried connecting DFC to any other devices or apps? Kinomap or Zwift are pretty easy to get up and running quickly with DFC.
Try re-seating the cables and swapping data ports on DFC.
When you power on DFC do you see a red light blinking through the ports for the first few minutes?
What are you using to power DFC? It works best using the cable that it comes with it. Using USB-C to USB-C cables can cause issues since DFC draws so little power that some USB-C chargers shut off power to it.
On your watch under DFC in Sensors does it say "Status Connected"?

**Comment by Artmidd** [comment]
Figured out the update and it worked.  Thank you!!On May 24, 2024, at 8:47 AM, ART MIDDLEMISS ***@***.***> wrote:﻿Hi thanks for getting back to me.  It's been working great for almost a year.  Nothing changed in the set up. It's hooked up to a peloton - first edition.  Not the plus. It's on a Fenix 7. I will try the firmware update though it may be too complicated for me! Have not tried connecting to other apps or devices. Tried re seating the cables. See the red light. Using the cord that came with it to power it. It does say status connected.  Just not getting the reading. I think it must be the recent garmin update.  I did notice that it goes in and out, so maybe that's the continual reset.  Was that a. Recent update from garmin that caused the issue?  Thanks again.  Art. On May 23, 2024, at 11:03 PM, Jason Veneman ***@***.***> wrote:﻿
Here’s a few things to check to help narrow down what may be causing issues.

Has it worked before or is this the first time you’re connecting DFC to anything?
What specific device is it that you're trying to connect?

This table lists which devices are known to work with DFC.
An update for certain Garmin devices (Epix (gen 2), Fenix 6/7, FR265, and possibly others) was causing DFC to continually reset.
The updated firmware that fixes the issue is here. See the Firmware Updates section in the User Guide for details on updating.


Have you tried connecting DFC to any other devices or apps? Kinomap or Zwift are pretty easy to get up and running quickly with DFC.
Try re-seating the cables and swapping data ports on DFC.
When you power on DFC do you see a red light blinking through the ports for the first few minutes?
What are you using to power DFC? It works best using the cable that it comes with it. Using USB-C to USB-C cables can cause issues since DFC draws so little power that some USB-C chargers shut off power to it.
On your watch under DFC in Sensors does it say "Status Connected"?

**Comment by VMUNIS** [comment]
@Artmidd I am having the same problem (Fenix 7). Can you walk me through how to do the update. This is on the Garmin watch, correct?

**Comment by Trebuin** [comment]
> @Artmidd I am having the same problem (Fenix 7). Can you walk me through how to do the update. This is on the Garmin watch, correct?

https://youtu.be/JNuzTvyP7F8

That will walk you through the upgrade on ios

**Comment by davidavallance1** [comment]
Happy to report that I installed the latest version of the firmware and I now have power and cadence.  This is for the Garmin 7x Pro.  I used the Android mobile DFU to complete the FW update. 
Thank you!!

**Comment by VMUNIS** [comment]
I tried to follow the video but it my app for the phone (Android) looks
nothing like the video. 🙃

Question: I'm trying to upgrade the firmware on the device over bluetooth,
correct?

Is there a way to connect the device to a computer and try it that way?

Can you give me step by step directions on how to do it?

Help! Lol! I miss my power data on my connect app.
