### ISSUE TITLE
Fenix 6 Saffire Does Not Detect

### ISSUE THREAD

**Issue by TheWebRecluse** [intelligenate/dfc#27]
I just purchased a Garmin Fenix 6 Saffire today for the purposes of using it with my Peloton and the DFC.
I have used DFC + Peloton via Zwift before though with not much accuracy at all.
I have been trying for about an hour to get the Garmin to pick up the Power sensor but it will not detect it.
I did the firmware beta update via the nRF software but it just will not even see the sensor.
I am pedaling and trying over and over and the Garmin just won't detect it.
I have tried unplugging and plugging it back in. I see a red light for a few seconds but then it goes off.
Zwift sees the DFC not my Garmin does not. Is there something I am doing wrong?

UPDATE: I finally have got it to connect but am I correct in understanding that it will not detect speed?

**Comment by veneman** [comment]
The firmware that DFC ships with only broadcasts power and cadence data to make it compatible with as many devices as possible. The[ beta release](https://github.com/intelligenate/dfc/releases/tag/speed-cadence-beta.1) broadcasts only speed and cadence but not power. We've done some work on an update that does power, speed, and cadence but have found that not all devices pick up on all of those bits of data.
