### ISSUE TITLE
Output not displaying on Peloton

### ISSUE THREAD

**Issue by infinus** [intelligenate/dfc#28]
I have connected the DFC as instructed to my Peloton, I do not have the bike+ just the regular bike. Initially I had the error on screen to verify connections, I verified connections and it did not go away but rebooting the peloton caused the error to go away but still no data displayed on the screen.

I can see power output on Apple Watch but no output on the Peloton screen. If I swap the connections on the DFC no more output it shown on either my Apple Watch nor my screen until I swap back at which point only my watch shows output. I have tried using another 3.5mm cable with the same results. 

I also tried a firmware update on the DFC with no change in behavior. Rebooted everything no change. Peloton Version 2.6.2429.2062429

I suppose it could be a physical port issue with the device but it is brand new out of the box.

**Comment by infinus** [comment]
I did some more testing, it still only sends data to external device in one orientation with the peloton plugged in to port near USB C port. My DFC has only 1 USB-C not two like mentioned elsewhere.

 Bike > DFC port near USB-C > Screen: Only data on Apple Watch
 Bike > DFC port on side > Screen: No data on screen nor Apple Watch
Bike > DFC port near USBC > not attached to screen: No data on screen nor Apple Watch/

so at some level the 3.5mm port on the Side is needed and detects but still not sure why it only works in one orientation. Not sure if this is due to peloton updating their software?

The connection error still displays from time to time along with a call customer support message but at least I can still get data on the watch.

**Comment by infinus** [comment]
@veneman is this project still active or should I reach out to crowd supply about a refund? I’d love to use the product but not very useful as is.

**Comment by veneman** [comment]
@infinus sorry, this one slipped through and I'm not sure if we've resolved it through other support channels. If you're still having issues let us know and we'll get it sorted. Sounds like it could be a problem with either the cables or jacks.
