### ISSUE TITLE
Garmin Fenix 5 Plus dropped 

### ISSUE THREAD

**Issue by Adanielcs** [intelligenate/dfc#5]
My Fenix 5 plus worked once and now won’t find the sensor.  I loaded the update.  Oddly, sometimes when I’m done with my ride I will get a notification on the watch that power is connected.
How can I make the connection when it will be useful?
Right now, this isn’t working.

**Comment by veneman** [comment]
Do you happen to know which update you tried? The [latest update](https://github.com/intelligenate/dfc/releases/tag/power-cadence-beta.3) released a few weeks ago has fixed dropouts for other devices.

**Comment by Adanielcs** [comment]
I did the one targeted at garmin dropouts.If there is a new one I will try again. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Jason Veneman ***@***.***> Date: 2/13/22  12:49 PM  (GMT-05:00) To: intelligenate/dfc ***@***.***> Cc: Adanielcs ***@***.***>, Author ***@***.***> Subject: Re: [intelligenate/dfc] Garmin Fenix 5 Plus dropped  (Issue #5) 
Do you happen to know which update you tried? The latest update released a few weeks ago has fixed dropouts for other devices.

**Comment by veneman** [comment]
A couple updates were released to try to fix the dropout issue. Give the latest one a try to see if that works.

**Comment by btbpsm** [comment]
I had a very similar symptoms and found that the dfc was losing power. I was powering the dfc from the tablet and the USB connection would loosen during my ride. With the known drop issue and the problem being intermittent I assumed it was dropping. It is worth checking if your are powering from the tablet.

Good luck with your troubleshooting

**Comment by Adanielcs** [comment]
The update did not help.  Power is not the issue, because the unit connects to my iPad for zwift.
It will not connect to Fenix 5 plus still.

**Comment by veneman** [comment]
It's good to hear that it works with Zwift for you but discouraging that the update didn't fix it. I've heard from a Fenix 5X user that DFC works well for them and was hoping the update created for Fenix 6 users would fix yours. 

Can you confirm that you tried the latest [power-cadence-beta.3](https://github.com/intelligenate/dfc/releases/tag/power-cadence-beta.3) update? Prior updates as well as the [speed-cadence-beta.1](https://github.com/intelligenate/dfc/releases/tag/speed-cadence-beta.1) update, which gives the option to use DFC as a speed and cadence sensor, do not have the timing fix that the power-cadence-beta.3 does. 

If the update is not working for you please reach out via the [contact info](https://intelligenate.com/#about) on our website to discuss next steps.
