### ISSUE TITLE
Can’t get it working 

### ISSUE THREAD

**Issue by Solace2020** [intelligenate/dfc#7]
Hi there. I can’t seem to get it working. The resistance and wattage numbers won’t show on the bike or the garmin paired with the dfc. Everything is plugged in - I’ve triple checked. Any tips?

**Comment by ragemarkus** [comment]
You have the start a ride on the peloton to make the stats available to the dfc.

**Comment by veneman** [comment]
Hey, sorry to hear you're having trouble. As mentioned above, you first have to be in a class or just ride for the data to be present for DFC. If you've done that and the numbers still aren't showing on the bike that may be an issue with the cabling. Send an email to support [at] intelligenate.com and we can help figure this out.
