### ISSUE TITLE
Compatible with Stryde bike?

### ISSUE THREAD

**Issue by brjadams** [intelligenate/dfc#8]
The cabling looks the same. No clue if data is compatible.

**Comment by veneman** [comment]
Good question but that's not something we've looked at or have heard about anyone else using with DFC. At this time we're not looking to expand to other platforms but we'll let you know if that changes or we get a report from someone who tries it.

**Comment by brjadams** [comment]
I think the connectors are the same. I'd be willing to test it if you had a
unit
