### ISSUE TITLE
Not working after recent Peloton update

### ISSUE THREAD

**Issue by melissalee08** [intelligenate/dfc#9]
I updated my Peloton firmware today and the unit has stopped working - it is not detecting metrics, even when the ride has started and I am pedaling. Unplugged, replugged, restarted, etc. Anyone experiencing the same issue?

**Comment by tonylchang** [comment]
I’ll try and let you know! Just hit update on my bike.

**Comment by tonylchang** [comment]
The DFC is still working for me after the latest peloton update. My Garmin was able to receive power and cadence data for my ride.

**Comment by veneman** [comment]
I don’t have any issues with apps or my Garmin with the latest update NQ.220527.A. I’m puzzled as to what could be causing the trouble. You’ve tried all the things I would have suggested.

**Comment by btbpsm** [comment]
which firmware release are you using?

**Comment by melissalee08** [comment]
I did the cable dance again this morning and it worked. Weird.
